name: Check Docs

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install markdownlint
        run: sudo npm install -g markdownlint-cli

      - name: Run Markdown Lint
        run: markdownlint -c .github/workflows/markdown_config.json ./

      - name: Check Typos
        uses: crate-ci/typos@v1.31.1
        with:
          files: 'docs/**/*.md docs/**/*.mdx'
          config: .github/workflows/typos.toml
          
      - name: Check with AutoCorrect
        uses: huacnlee/autocorrect-action@v2
        with:
          args: --lint docs/**/*.md docs/**/*.mdx

      - name: Report ReviewDog
        if: always()
        uses: tomchon/autocorrect-action@fix/review-dog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          reviewdog: true
          args: ./docs/**/*.md ./docs/**/*.mdx
      
      - name: Check Markdown Lint Cli2
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          config: '.github/workflows/.markdownlint-cli2.jsonc'
          globs: 'docs/**/*.md,docs/**/*.mdx'
      

  build:
    needs:
      - check
    uses: ./.github/workflows/build_docs.yaml